name: Deploy Updater to Stage
on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Debug secrets
        run: |
          echo "PORT: ${DEPLOY_PORT_STAGE:0:3}***"
          echo "HOST: ${DEPLOY_HOST_STAGE:0:5}***"
        env:
          DEPLOY_PORT_STAGE: ${{ secrets.DEPLOY_PORT_STAGE }}
          DEPLOY_HOST_STAGE: ${{ secrets.DEPLOY_HOST_STAGE }}

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.STAGE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.DEPLOY_PORT_STAGE }} -H ${{ secrets.DEPLOY_HOST_STAGE }} >> ~/.ssh/known_hosts

      - name: Deploy plugin via rsync
        run: |
          rsync -avz -e "ssh -p ${{ secrets.DEPLOY_PORT_STAGE }}" \
            ./wp-content/plugins/my-plugin/ \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST_STAGE }}:/share/sites/staging.gayety.com/htdocs/wp-content/plugins/jwplayer-metadata-updater/
