name: Deploy Updater to Stage
on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Debug secrets
        run: |
          echo "PORT: ${DEPLOY_PORT_STAGE:0:30}***"
          echo "HOST: ${DEPLOY_HOST_STAGE:0:50}***"
        env:
          DEPLOY_PORT_STAGE: ${{ secrets.DEPLOY_PORT_STAGE }}
          DEPLOY_HOST_STAGE: ${{ secrets.DEPLOY_HOST_STAGE }}

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: vpn.leviathan.ateamservers.com
          username: github
          key: ${{ secrets.STAGE_SSH_KEY }}
          port: 2220
          script: whoami
          debug: true


      - name: Deploy plugin via rsync
        run: |
          rsync -avz -e "ssh -p ${{ secrets.DEPLOY_PORT_STAGE }}" \
            ./wp-content/plugins/my-plugin/ \
            ${{ secrets.DEPLOY_USER }}@vpn.leviathan.ateamservers.com:/share/sites/staging.gayety.com/htdocs/wp-content/plugins/jwplayer-metadata-updater/
